### ISSUE TITLE
Questions final assignment

### ISSUE THREAD

**Issue by sdaza** [sdaza/survey-methods#1]
Here, I will post all questions (and answers) I receive on the final assignment. You can also write your questions directly in this issue. Thanks!

**Comment by sdaza** [comment]
> I am not sure I am correctly understanding the question 3.b. I see that for estimating MOE it is required to use an approximation of the population variance, and a 0.5 in the proportion could be used to get the maximum. However, I do not see how this links to the question on background information. 

That question is about the assumptions you need for MOE estimation. In general, studies give you a MOE with max variance (0.5), but they don't clarify all the assumptions behind that estimation. In other words, check the information you will need to assess the MOE estimation (beyond the formula used). 

> Second, regarding format, could I send an hmtl file containing the code and results for exercises 4 and 5 (along with the answers in the main word, of course)?

Please, try to put everything into a pdf file, so that, it is easier to review. 

Thanks!
Sebastian

**Comment by sdaza** [comment]
>  I'm not really sure I understood the exercise 4 correctly. The goal in the part a) is to estimate the proportion only with the data provided, or to do so using design weights? And if it's the first case, then should we compute the design effect of not using those weights?

The idea of this exercise is to use `raking` to estimate drug use. You don't have any information on the design of the sample, only marginal distributions. To compute the DEFF of weights, you have examples of how to do it in the slides and code available for the course.

Thanks!
Sebastian

**Comment by alejandroaisam** [comment]
Good afternoon, Sebastian

I don't understand what do we have to do exactly in exercise five. Do we have to construct a sample from this list? If so, how many people? I understand that we have to select an element every 42, but I don't what to do next. 

Thanks!

**Comment by sdaza** [comment]
@AlejandroAisa36 You need to select (sample) blocks using systematic PPS using the rule: start with 6 and use interval 41. Check the chapter on sampling in Groves' book.

**Comment by Nienke-Visscher** [comment]
Hello! In question 6 i am a bit confused with the following sentence: "After the survey is completed, someone suggests assessing its effectiveness by comparing the demographic distributions (such as age, sex, race/ethnicity, and gender) of the "most knowledgeable" health informant with the demographic distributions of adults from the previous census." Do I understand correctly that in the years before they didn't ask for the most knowledgeable person to provide the answer? And they want to see the demographic changes between asking for the most knowledgeable person and not asking for the most knowledgeable person?
