### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by sdaza** [sdaza/survey-methods#2]
Here you can post all your questions on assignment 1. Questions I got via email: 

1. I am not sure if Frame Error is the same as Coverage Error.

> The coverage error may be caused by sampling frame error or other factors, such as excluding certain population groups for convenience.

2. When calculating the MOE for the entire sample, which value is "n"? Is it the total number of participants in the sample, which is 3642, or the 300 that have been selected? I have attached the calculations I have made.

> Sample is just a fraction of the population. MOE is related to a sample, not the population.

**Comment by sdaza** [comment]
Questions I got via email: 

1. I am not sure if Frame Error is the same as Coverage Error.

> The coverage error may be caused by sampling frame error or other factors, such as excluding certain population groups for convenience.

3. When calculating the MOE for the entire sample, which value is "n"? Is it the total number of participants in the sample, which is 3642, or the 300 that have been selected? I have attached the calculations I have made.

> Sample is just a fraction of the population. MOE is related to a sample, not the population.

**Comment by alexandra-rose** [comment]
EDIT: I think I actually found the answer I was looking for with the proportions definition and by using binomial distributions. So never mind!

About question 2:

I'm confused as to how we get the standard error, the standard error is only related to the sample, right? And can we say that 174 is the mean of the sample in this case? Or if not how do we find the mean and standard deviation?

Thanks,

**Comment by sdaza** [comment]
> EDIT: I think I actually found the answer I was looking for with the proportions definition and by using binomial distributions. So never mind!

Good!

> I'm confused as to how we get the standard error, the standard error is only related to the sample, right? And can we say that 174 is the mean of the sample in this case? Or if not how do we find the mean and standard deviation?

Standard error is the standard deviation of the sampling distribution (so, it relates only to samples). Use the corresponding formula to the problem at hand. There are examples in the notebooks and slides.

**Comment by Nienke-Visscher** [comment]
Hi! For question 3-D: MOE only for group C, should we compose the MOE completely by itself like this: serr(61, N = 343, p = 0.51) (note that the the n  for this strata is computed with w=0.3 to make the group larger in relation to the other groups) or in relation to the other strata serr(300, N=N, p=prop_eng) (note that N is the total population and p = proportion of engagement). This function gives the MOE for all for all 4 strata and hence we can read the MOE for just C as well.

**Comment by sdaza** [comment]
> Hi! For question 3-D: MOE only for group C, should we compose the MOE completely by itself like this: serr(61, N = 343, p = 0.51) (note that the the n for this strata is computed with w=0.3 to make the group larger in relation to the other groups) or in relation to the other strata serr(300, N=N, p=prop_eng) (note that N is the total population and p = proportion of engagement). This function gives the MOE for all for all 4 strata and hence we can read the MOE for just C as well.

To calculate the margin of error (MOE) for C, you can use group C as the sample. To estimate the MOE for all strata, you will need to apply the stratification formula (which we will discuss in the next class).

**Comment by Nienke-Visscher** [comment]
Thank you!

**Comment by claraespinosa** [comment]
Hello! I was trying to use the package of sampler, but I am still getting the following error: Skipping install of 'sampler' from a github remote, the SHA1 (99b279a0) has not changed since last install. Use `force = TRUE` to force installation. How can I solve this?

**Comment by sdaza** [comment]
> Hello! I was trying to use the package of sampler, but I am still getting the following error: Skipping install of 'sampler' from a github remote, the SHA1 (99b279a0) has not changed since last install. Use `force = TRUE` to force installation. How can I solve this?

It seems that the package is already installed. Could you please try running `library(sampler)` and then execute `ssize(.05)`?
